// LOCALHOST
### create fakads
curl -X POST http://localhost:8080/ \
-H "Content-Type: application/json" \
-d '{
  "firstName": "Hope",
  "middleName": "A",
  "lastName": "Simon",
  "gender": "Female",
  "occupation": "Software Engineer",
  "position": "Developer",
  "officeAddress": "123 Tech Street",
  "headquartersLocation": "Tech City HQ",
  "subBusinessBranches": ["Branch 1", "Branch 2"],
  "contactNumber": "+1234567890",
  "email": "hopesimon@gmail.com",
  "socialMediaHandles": {
    "linkedin": "linkedin.com/in/hopesimon",
    "twitter": "twitter.com/hopesimon"
  },
  "passportPhotograph": "base64ImageString"
}'


### get all fakads
GET http://localhost:8080/

### get fakads by id
GET http://localhost:8080/666b5b265d05e7ee0d9d65d4

### update fakad
curl -X PUT http://localhost:8080/666b5b6e5d05e7ee0d9d65d5 \
-H "Content-Type: application/json" \
-d '{
  "firstName": "John",
  "middleName": "B",
  "lastName": "Doe",
  "gender": "Male",
  "occupation": "Data Scientist",
  "position": "Senior Analyst",
  "officeAddress": "456 Data Avenue",
  "headquartersLocation": "Data City HQ",
  "subBusinessBranches": ["Branch 3", "Branch 4"],
  "contactNumber": "+9876543210",
  "email": "johndoe@example.com",
  "socialMediaHandles": {
    "linkedin": "linkedin.com/in/johndoe",
    "twitter": "twitter.com/johndoe"
  },
  "passportPhotograph": "newBase64ImageString"
}'

### delete a fakad
DELETE http://localhost:8080/666b5b265d05e7ee0d9d65d4